### ISSUE TITLE
Broken links to tts.eng.br

### ISSUE THREAD

**Issue by quinncomendant** [scribblemaniac/Fibonnac-iClock#3]
Your links to Thiago Sá's website are broken. The error is: `tts.eng.br’s server IP address could not be found.` Do you know if the website moved? Perhaps you can link to the same pages archived in the Wayback Machine, e.g., https://web.archive.org/web/20190331014356/tts.eng.br/the-fibonacci-clock/

**Comment by scribblemaniac** [comment]
Updated link to https://github.com/thiagotts/fibonacci-clock. Thanks!
